var Training = `
<div class="w3-row w3-content">
        <div  id="textContent" class="w3-light-grey w3-padding-large w3-padding-32 w3-margin-top">
                <h1>Training</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac varius ipsum, et malesuada sapien. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus a placerat justo. Proin facilisis metus massa, et condimentum urna eleifend in. Sed euismod metus eleifend lectus placerat, ut aliquet ligula lobortis. Morbi eu ornare massa. Proin condimentum lacus ac justo ullamcorper, eget lobortis metus egestas. Fusce tortor ligula, eleifend at dapibus eu, fringilla in nunc. Vestibulum vestibulum ultrices enim non consectetur. Maecenas id lacus quis tortor ultricies pretium. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin ullamcorper imperdiet neque consectetur placerat. Aliquam nunc velit, congue in sapien at, scelerisque sollicitudin dui. Proin vitae augue ut lacus pellentesque accumsan. Morbi porttitor diam id mauris molestie, ultrices rhoncus mauris feugiat. Duis pharetra ligula augue, eget tempus lectus venenatis id.</p>

                <p>Ut interdum libero in mi placerat, in convallis velit convallis. Integer a lectus ut nunc ultricies vehicula molestie sed ex. Ut facilisis, eros a semper malesuada, nisi est porta quam, in tincidunt orci justo quis eros. Donec eu urna ut augue porttitor euismod nec a lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed luctus nisl malesuada arcu eleifend, molestie ultrices tortor ornare. Morbi sed faucibus sapien. Sed vel lectus eros. Morbi sagittis ultricies ex nec feugiat. Curabitur ut cursus nunc.</p>

                <p>Fusce tempus volutpat justo, ut fermentum dolor ultricies eget. Aliquam tempus a augue vel scelerisque. In ac leo porttitor, pretium ex et, ornare ante. Pellentesque egestas dui nec enim euismod, vitae vestibulum velit aliquam. Nunc tincidunt nec nibh eget vulputate. Aenean fermentum elit eu justo imperdiet hendrerit. Quisque commodo, libero id tristique vehicula, nisl leo commodo elit, ut mollis libero dolor in ex. Cras iaculis tempus lectus non molestie. Cras id felis non dui porta venenatis nec sed neque. Vestibulum varius laoreet auctor. Nullam at maximus mi.</p>

                <p>Aenean semper libero sed libero congue imperdiet. Maecenas nec nunc vel lacus pretium eleifend vitae at nunc. Nulla et nisl condimentum, cursus justo vitae, laoreet massa. Fusce hendrerit auctor sem, id porta turpis feugiat in. Vestibulum ullamcorper ex quis suscipit tincidunt. Nullam varius molestie porttitor. Nulla facilisi. Maecenas suscipit elit risus, a tincidunt orci posuere vitae. Nunc maximus elementum dui, id tempor magna viverra sit amet. Proin auctor orci in diam vehicula, sit amet vulputate dolor porta. Mauris nec sollicitudin ante. Proin non urna scelerisque, rhoncus lorem finibus, luctus purus. Duis pretium lobortis scelerisque. Nam iaculis nibh in ex tempor, sit amet tincidunt libero pharetra.</p>

                
        </div>
    </div>
`;