//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.ServiceReferenceCities {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://cegep-heritage.qc.ca/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CityDetail", Namespace="http://cegep-heritage.qc.ca/")]
    [System.SerializableAttribute()]
    public partial class CityDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int _idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServices.ServiceReferenceCities.Coordinates coordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                if ((object.ReferenceEquals(this.countryField, value) != true)) {
                    this.countryField = value;
                    this.RaisePropertyChanged("country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WebServices.ServiceReferenceCities.Coordinates coord {
            get {
                return this.coordField;
            }
            set {
                if ((object.ReferenceEquals(this.coordField, value) != true)) {
                    this.coordField = value;
                    this.RaisePropertyChanged("coord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Coordinates", Namespace="http://cegep-heritage.qc.ca/")]
    [System.SerializableAttribute()]
    public partial class Coordinates : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double lonField;
        
        private double latField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double lon {
            get {
                return this.lonField;
            }
            set {
                if ((this.lonField.Equals(value) != true)) {
                    this.lonField = value;
                    this.RaisePropertyChanged("lon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double lat {
            get {
                return this.latField;
            }
            set {
                if ((this.latField.Equals(value) != true)) {
                    this.latField = value;
                    this.RaisePropertyChanged("lat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cegep-heritage.qc.ca/", ConfigurationName="ServiceReferenceCities.CitiesSoap")]
    public interface CitiesSoap {
        
        // CODEGEN: Generating message contract since element name GetCountriesResult from namespace http://cegep-heritage.qc.ca/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cegep-heritage.qc.ca/GetCountries", ReplyAction="*")]
        WebServices.ServiceReferenceCities.GetCountriesResponse GetCountries(WebServices.ServiceReferenceCities.GetCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cegep-heritage.qc.ca/GetCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices.ServiceReferenceCities.GetCountriesResponse> GetCountriesAsync(WebServices.ServiceReferenceCities.GetCountriesRequest request);
        
        // CODEGEN: Generating message contract since element name _country from namespace http://cegep-heritage.qc.ca/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cegep-heritage.qc.ca/GetCities", ReplyAction="*")]
        WebServices.ServiceReferenceCities.GetCitiesResponse GetCities(WebServices.ServiceReferenceCities.GetCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cegep-heritage.qc.ca/GetCities", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices.ServiceReferenceCities.GetCitiesResponse> GetCitiesAsync(WebServices.ServiceReferenceCities.GetCitiesRequest request);
        
        // CODEGEN: Generating message contract since element name GetCityDetailResult from namespace http://cegep-heritage.qc.ca/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cegep-heritage.qc.ca/GetCityDetail", ReplyAction="*")]
        WebServices.ServiceReferenceCities.GetCityDetailResponse GetCityDetail(WebServices.ServiceReferenceCities.GetCityDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cegep-heritage.qc.ca/GetCityDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices.ServiceReferenceCities.GetCityDetailResponse> GetCityDetailAsync(WebServices.ServiceReferenceCities.GetCityDetailRequest request);
        
        // CODEGEN: Generating message contract since element name GetCityWeatherResult from namespace http://cegep-heritage.qc.ca/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cegep-heritage.qc.ca/GetCityWeather", ReplyAction="*")]
        WebServices.ServiceReferenceCities.GetCityWeatherResponse GetCityWeather(WebServices.ServiceReferenceCities.GetCityWeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cegep-heritage.qc.ca/GetCityWeather", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices.ServiceReferenceCities.GetCityWeatherResponse> GetCityWeatherAsync(WebServices.ServiceReferenceCities.GetCityWeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cegep-heritage.qc.ca/GetCitiesDistance", ReplyAction="*")]
        double GetCitiesDistance(int _cityId1, int _cityId2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cegep-heritage.qc.ca/GetCitiesDistance", ReplyAction="*")]
        System.Threading.Tasks.Task<double> GetCitiesDistanceAsync(int _cityId1, int _cityId2);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountries", Namespace="http://cegep-heritage.qc.ca/", Order=0)]
        public WebServices.ServiceReferenceCities.GetCountriesRequestBody Body;
        
        public GetCountriesRequest() {
        }
        
        public GetCountriesRequest(WebServices.ServiceReferenceCities.GetCountriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCountriesRequestBody {
        
        public GetCountriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountriesResponse", Namespace="http://cegep-heritage.qc.ca/", Order=0)]
        public WebServices.ServiceReferenceCities.GetCountriesResponseBody Body;
        
        public GetCountriesResponse() {
        }
        
        public GetCountriesResponse(WebServices.ServiceReferenceCities.GetCountriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cegep-heritage.qc.ca/")]
    public partial class GetCountriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServices.ServiceReferenceCities.ArrayOfString GetCountriesResult;
        
        public GetCountriesResponseBody() {
        }
        
        public GetCountriesResponseBody(WebServices.ServiceReferenceCities.ArrayOfString GetCountriesResult) {
            this.GetCountriesResult = GetCountriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCities", Namespace="http://cegep-heritage.qc.ca/", Order=0)]
        public WebServices.ServiceReferenceCities.GetCitiesRequestBody Body;
        
        public GetCitiesRequest() {
        }
        
        public GetCitiesRequest(WebServices.ServiceReferenceCities.GetCitiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cegep-heritage.qc.ca/")]
    public partial class GetCitiesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _country;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _maxCount;
        
        public GetCitiesRequestBody() {
        }
        
        public GetCitiesRequestBody(string _country, string _maxCount) {
            this._country = _country;
            this._maxCount = _maxCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesResponse", Namespace="http://cegep-heritage.qc.ca/", Order=0)]
        public WebServices.ServiceReferenceCities.GetCitiesResponseBody Body;
        
        public GetCitiesResponse() {
        }
        
        public GetCitiesResponse(WebServices.ServiceReferenceCities.GetCitiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cegep-heritage.qc.ca/")]
    public partial class GetCitiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServices.ServiceReferenceCities.CityDetail[] GetCitiesResult;
        
        public GetCitiesResponseBody() {
        }
        
        public GetCitiesResponseBody(WebServices.ServiceReferenceCities.CityDetail[] GetCitiesResult) {
            this.GetCitiesResult = GetCitiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityDetail", Namespace="http://cegep-heritage.qc.ca/", Order=0)]
        public WebServices.ServiceReferenceCities.GetCityDetailRequestBody Body;
        
        public GetCityDetailRequest() {
        }
        
        public GetCityDetailRequest(WebServices.ServiceReferenceCities.GetCityDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cegep-heritage.qc.ca/")]
    public partial class GetCityDetailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int _id;
        
        public GetCityDetailRequestBody() {
        }
        
        public GetCityDetailRequestBody(int _id) {
            this._id = _id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityDetailResponse", Namespace="http://cegep-heritage.qc.ca/", Order=0)]
        public WebServices.ServiceReferenceCities.GetCityDetailResponseBody Body;
        
        public GetCityDetailResponse() {
        }
        
        public GetCityDetailResponse(WebServices.ServiceReferenceCities.GetCityDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cegep-heritage.qc.ca/")]
    public partial class GetCityDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServices.ServiceReferenceCities.CityDetail GetCityDetailResult;
        
        public GetCityDetailResponseBody() {
        }
        
        public GetCityDetailResponseBody(WebServices.ServiceReferenceCities.CityDetail GetCityDetailResult) {
            this.GetCityDetailResult = GetCityDetailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityWeatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityWeather", Namespace="http://cegep-heritage.qc.ca/", Order=0)]
        public WebServices.ServiceReferenceCities.GetCityWeatherRequestBody Body;
        
        public GetCityWeatherRequest() {
        }
        
        public GetCityWeatherRequest(WebServices.ServiceReferenceCities.GetCityWeatherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cegep-heritage.qc.ca/")]
    public partial class GetCityWeatherRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int _cityId;
        
        public GetCityWeatherRequestBody() {
        }
        
        public GetCityWeatherRequestBody(int _cityId) {
            this._cityId = _cityId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityWeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityWeatherResponse", Namespace="http://cegep-heritage.qc.ca/", Order=0)]
        public WebServices.ServiceReferenceCities.GetCityWeatherResponseBody Body;
        
        public GetCityWeatherResponse() {
        }
        
        public GetCityWeatherResponse(WebServices.ServiceReferenceCities.GetCityWeatherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cegep-heritage.qc.ca/")]
    public partial class GetCityWeatherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetCityWeatherResult;
        
        public GetCityWeatherResponseBody() {
        }
        
        public GetCityWeatherResponseBody(System.Xml.Linq.XElement GetCityWeatherResult) {
            this.GetCityWeatherResult = GetCityWeatherResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CitiesSoapChannel : WebServices.ServiceReferenceCities.CitiesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CitiesSoapClient : System.ServiceModel.ClientBase<WebServices.ServiceReferenceCities.CitiesSoap>, WebServices.ServiceReferenceCities.CitiesSoap {
        
        public CitiesSoapClient() {
        }
        
        public CitiesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CitiesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CitiesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CitiesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.ServiceReferenceCities.GetCountriesResponse WebServices.ServiceReferenceCities.CitiesSoap.GetCountries(WebServices.ServiceReferenceCities.GetCountriesRequest request) {
            return base.Channel.GetCountries(request);
        }
        
        public WebServices.ServiceReferenceCities.ArrayOfString GetCountries() {
            WebServices.ServiceReferenceCities.GetCountriesRequest inValue = new WebServices.ServiceReferenceCities.GetCountriesRequest();
            inValue.Body = new WebServices.ServiceReferenceCities.GetCountriesRequestBody();
            WebServices.ServiceReferenceCities.GetCountriesResponse retVal = ((WebServices.ServiceReferenceCities.CitiesSoap)(this)).GetCountries(inValue);
            return retVal.Body.GetCountriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices.ServiceReferenceCities.GetCountriesResponse> WebServices.ServiceReferenceCities.CitiesSoap.GetCountriesAsync(WebServices.ServiceReferenceCities.GetCountriesRequest request) {
            return base.Channel.GetCountriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServices.ServiceReferenceCities.GetCountriesResponse> GetCountriesAsync() {
            WebServices.ServiceReferenceCities.GetCountriesRequest inValue = new WebServices.ServiceReferenceCities.GetCountriesRequest();
            inValue.Body = new WebServices.ServiceReferenceCities.GetCountriesRequestBody();
            return ((WebServices.ServiceReferenceCities.CitiesSoap)(this)).GetCountriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.ServiceReferenceCities.GetCitiesResponse WebServices.ServiceReferenceCities.CitiesSoap.GetCities(WebServices.ServiceReferenceCities.GetCitiesRequest request) {
            return base.Channel.GetCities(request);
        }
        
        public WebServices.ServiceReferenceCities.CityDetail[] GetCities(string _country, string _maxCount) {
            WebServices.ServiceReferenceCities.GetCitiesRequest inValue = new WebServices.ServiceReferenceCities.GetCitiesRequest();
            inValue.Body = new WebServices.ServiceReferenceCities.GetCitiesRequestBody();
            inValue.Body._country = _country;
            inValue.Body._maxCount = _maxCount;
            WebServices.ServiceReferenceCities.GetCitiesResponse retVal = ((WebServices.ServiceReferenceCities.CitiesSoap)(this)).GetCities(inValue);
            return retVal.Body.GetCitiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices.ServiceReferenceCities.GetCitiesResponse> WebServices.ServiceReferenceCities.CitiesSoap.GetCitiesAsync(WebServices.ServiceReferenceCities.GetCitiesRequest request) {
            return base.Channel.GetCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServices.ServiceReferenceCities.GetCitiesResponse> GetCitiesAsync(string _country, string _maxCount) {
            WebServices.ServiceReferenceCities.GetCitiesRequest inValue = new WebServices.ServiceReferenceCities.GetCitiesRequest();
            inValue.Body = new WebServices.ServiceReferenceCities.GetCitiesRequestBody();
            inValue.Body._country = _country;
            inValue.Body._maxCount = _maxCount;
            return ((WebServices.ServiceReferenceCities.CitiesSoap)(this)).GetCitiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.ServiceReferenceCities.GetCityDetailResponse WebServices.ServiceReferenceCities.CitiesSoap.GetCityDetail(WebServices.ServiceReferenceCities.GetCityDetailRequest request) {
            return base.Channel.GetCityDetail(request);
        }
        
        public WebServices.ServiceReferenceCities.CityDetail GetCityDetail(int _id) {
            WebServices.ServiceReferenceCities.GetCityDetailRequest inValue = new WebServices.ServiceReferenceCities.GetCityDetailRequest();
            inValue.Body = new WebServices.ServiceReferenceCities.GetCityDetailRequestBody();
            inValue.Body._id = _id;
            WebServices.ServiceReferenceCities.GetCityDetailResponse retVal = ((WebServices.ServiceReferenceCities.CitiesSoap)(this)).GetCityDetail(inValue);
            return retVal.Body.GetCityDetailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices.ServiceReferenceCities.GetCityDetailResponse> WebServices.ServiceReferenceCities.CitiesSoap.GetCityDetailAsync(WebServices.ServiceReferenceCities.GetCityDetailRequest request) {
            return base.Channel.GetCityDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServices.ServiceReferenceCities.GetCityDetailResponse> GetCityDetailAsync(int _id) {
            WebServices.ServiceReferenceCities.GetCityDetailRequest inValue = new WebServices.ServiceReferenceCities.GetCityDetailRequest();
            inValue.Body = new WebServices.ServiceReferenceCities.GetCityDetailRequestBody();
            inValue.Body._id = _id;
            return ((WebServices.ServiceReferenceCities.CitiesSoap)(this)).GetCityDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.ServiceReferenceCities.GetCityWeatherResponse WebServices.ServiceReferenceCities.CitiesSoap.GetCityWeather(WebServices.ServiceReferenceCities.GetCityWeatherRequest request) {
            return base.Channel.GetCityWeather(request);
        }
        
        public System.Xml.Linq.XElement GetCityWeather(int _cityId) {
            WebServices.ServiceReferenceCities.GetCityWeatherRequest inValue = new WebServices.ServiceReferenceCities.GetCityWeatherRequest();
            inValue.Body = new WebServices.ServiceReferenceCities.GetCityWeatherRequestBody();
            inValue.Body._cityId = _cityId;
            WebServices.ServiceReferenceCities.GetCityWeatherResponse retVal = ((WebServices.ServiceReferenceCities.CitiesSoap)(this)).GetCityWeather(inValue);
            return retVal.Body.GetCityWeatherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices.ServiceReferenceCities.GetCityWeatherResponse> WebServices.ServiceReferenceCities.CitiesSoap.GetCityWeatherAsync(WebServices.ServiceReferenceCities.GetCityWeatherRequest request) {
            return base.Channel.GetCityWeatherAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServices.ServiceReferenceCities.GetCityWeatherResponse> GetCityWeatherAsync(int _cityId) {
            WebServices.ServiceReferenceCities.GetCityWeatherRequest inValue = new WebServices.ServiceReferenceCities.GetCityWeatherRequest();
            inValue.Body = new WebServices.ServiceReferenceCities.GetCityWeatherRequestBody();
            inValue.Body._cityId = _cityId;
            return ((WebServices.ServiceReferenceCities.CitiesSoap)(this)).GetCityWeatherAsync(inValue);
        }
        
        public double GetCitiesDistance(int _cityId1, int _cityId2) {
            return base.Channel.GetCitiesDistance(_cityId1, _cityId2);
        }
        
        public System.Threading.Tasks.Task<double> GetCitiesDistanceAsync(int _cityId1, int _cityId2) {
            return base.Channel.GetCitiesDistanceAsync(_cityId1, _cityId2);
        }
    }
}
